/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `wp_comments` (
  `comment_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `comment_post_ID` bigint(20) unsigned NOT NULL DEFAULT 0,
  `comment_author` tinytext NOT NULL,
  `comment_author_email` varchar(100) NOT NULL DEFAULT '',
  `comment_author_url` varchar(200) NOT NULL DEFAULT '',
  `comment_author_IP` varchar(100) NOT NULL DEFAULT '',
  `comment_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_content` text NOT NULL,
  `comment_karma` int(11) NOT NULL DEFAULT 0,
  `comment_approved` varchar(20) NOT NULL DEFAULT '1',
  `comment_agent` varchar(255) NOT NULL DEFAULT '',
  `comment_type` varchar(20) NOT NULL DEFAULT 'comment',
  `comment_parent` bigint(20) unsigned NOT NULL DEFAULT 0,
  `user_id` bigint(20) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`comment_ID`),
  KEY `comment_post_ID` (`comment_post_ID`),
  KEY `comment_approved_date_gmt` (`comment_approved`,`comment_date_gmt`),
  KEY `comment_date_gmt` (`comment_date_gmt`),
  KEY `comment_parent` (`comment_parent`),
  KEY `comment_author_email` (`comment_author_email`(10)),
  KEY `woo_idx_comment_type` (`comment_type`)
) ENGINE=InnoDB AUTO_INCREMENT=102 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (2,1255,'WooCommerce','woocommerce@arcapet.cl','','','2020-05-25 18:39:42','2020-05-25 18:39:42','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (3,1256,'WooCommerce','woocommerce@arcapet.cl','','','2020-05-25 18:39:42','2020-05-25 18:39:42','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (4,1264,'WooCommerce','woocommerce@arcapet.cl','','','2020-05-25 19:30:33','2020-05-25 19:30:33','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (5,1264,'WooCommerce','woocommerce@arcapet.cl','','','2020-05-25 19:30:33','2020-05-25 19:30:33','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (6,1258,'WooCommerce','woocommerce@arcapet.cl','','','2020-05-25 22:28:59','2020-05-25 22:28:59','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (7,1259,'WooCommerce','woocommerce@arcapet.cl','','','2020-05-25 22:28:59','2020-05-25 22:28:59','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (8,1261,'WooCommerce','woocommerce@arcapet.cl','','','2020-05-25 22:28:59','2020-05-25 22:28:59','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (9,1262,'WooCommerce','woocommerce@arcapet.cl','','','2020-05-25 22:28:59','2020-05-25 22:28:59','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (10,1263,'WooCommerce','woocommerce@arcapet.cl','','','2020-05-25 22:28:59','2020-05-25 22:28:59','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (11,1264,'danarcapet','admin@ytchile.com','','','2020-05-28 22:34:40','2020-05-28 22:34:40','Estado del pedido cambiado por edición en lote: El estado del pedido cambió de Procesando a Completado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (12,4229,'WooCommerce','woocommerce@arcapet.cl','','','2020-06-30 21:04:56','2020-06-30 21:04:56','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (13,4229,'WooCommerce','woocommerce@arcapet.cl','','','2020-06-30 21:04:56','2020-06-30 21:04:56','Niveles de inventario reducidos: Royal Canin Yorkshire Terrier Adulto 2.5Kg (#1648) 10&rarr;9',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (14,4229,'WooCommerce','woocommerce@arcapet.cl','','','2020-06-30 21:04:56','2020-06-30 21:04:56','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (15,4753,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-06 01:27:52','2020-07-06 01:27:52','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (16,4753,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-06 01:27:52','2020-07-06 01:27:52','Niveles de inventario reducidos: Royal Canin Pug Junior (#960) 10&rarr;9',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (17,4753,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-06 01:27:52','2020-07-06 01:27:52','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (18,4233,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-09 07:08:17','2020-07-09 07:08:17','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (19,4751,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-09 07:08:18','2020-07-09 07:08:18','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (20,5155,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-11 15:18:42','2020-07-11 15:18:42','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (21,5157,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-11 21:03:33','2020-07-11 21:03:33','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (22,5255,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-12 03:04:43','2020-07-12 03:04:43','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (23,5257,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-12 04:05:00','2020-07-12 04:05:00','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (24,5439,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-14 15:06:09','2020-07-14 15:06:09','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (25,5439,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-14 15:06:09','2020-07-14 15:06:09','Niveles de inventario reducidos: PET’S DREAM - Sustrato ecológico de papel (#1050) 10&rarr;6',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (26,5439,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-14 15:06:09','2020-07-14 15:06:09','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (27,5584,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-16 17:33:46','2020-07-16 17:33:46','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (28,5584,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-16 17:33:46','2020-07-16 17:33:46','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (29,5613,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-17 20:05:35','2020-07-17 20:05:35','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (30,5769,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-21 19:33:40','2020-07-21 19:33:40','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (31,5769,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-21 19:33:40','2020-07-21 19:33:40','Niveles de inventario reducidos: Canish Espuma Shampoo en seco (#4392) 10&rarr;9',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (32,5769,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-21 19:33:40','2020-07-21 19:33:40','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (33,5767,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-21 20:56:49','2020-07-21 20:56:49','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (34,5768,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-21 20:56:49','2020-07-21 20:56:49','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (35,5924,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-26 16:55:31','2020-07-26 16:55:31','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (36,5924,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-26 16:55:31','2020-07-26 16:55:31','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (37,5967,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-30 04:22:45','2020-07-30 04:22:45','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (38,5967,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-30 04:22:45','2020-07-30 04:22:45','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (39,5968,'WooCommerce','woocommerce@arcapet.cl','','','2020-07-30 18:28:25','2020-07-30 18:28:25','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (40,6021,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-05 14:27:13','2020-08-05 14:27:13','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (41,6021,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-05 14:27:13','2020-08-05 14:27:13','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (42,6023,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-09 15:09:00','2020-08-09 15:09:00','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (43,6023,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-09 15:09:00','2020-08-09 15:09:00','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (44,6028,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-11 22:21:15','2020-08-11 22:21:15','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (45,6028,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-11 22:21:15','2020-08-11 22:21:15','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (46,6032,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-12 17:37:05','2020-08-12 17:37:05','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (47,6032,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-12 17:37:05','2020-08-12 17:37:05','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (48,6032,'Gerardo Corvalan','infoarcapet@gmail.com','','','2020-08-12 21:46:27','2020-08-12 21:46:27','El estado del pedido cambió de Procesando a Completado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (49,6028,'Gerardo Corvalan','infoarcapet@gmail.com','','','2020-08-12 21:47:45','2020-08-12 21:47:45','El estado del pedido cambió de Procesando a Completado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (50,6023,'Gerardo Corvalan','infoarcapet@gmail.com','','','2020-08-12 21:47:50','2020-08-12 21:47:50','El estado del pedido cambió de Procesando a Completado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (51,6021,'Gerardo Corvalan','infoarcapet@gmail.com','','','2020-08-12 21:47:54','2020-08-12 21:47:54','El estado del pedido cambió de Procesando a Completado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (52,6110,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-14 03:58:57','2020-08-14 03:58:57','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (53,6110,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-14 03:58:57','2020-08-14 03:58:57','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (54,6095,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-14 04:35:52','2020-08-14 04:35:52','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (55,6109,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-14 04:35:52','2020-08-14 04:35:52','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (56,6111,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-14 15:08:29','2020-08-14 15:08:29','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (57,6124,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-14 21:01:38','2020-08-14 21:01:38','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (58,6129,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-14 21:32:22','2020-08-14 21:32:22','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (59,6129,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-14 21:32:23','2020-08-14 21:32:23','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (60,6137,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-15 04:47:31','2020-08-15 04:47:31','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (61,6137,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-15 04:47:31','2020-08-15 04:47:31','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (62,6139,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-15 15:33:20','2020-08-15 15:33:20','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (63,6139,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-15 15:33:20','2020-08-15 15:33:20','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (64,6138,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-15 16:49:58','2020-08-15 16:49:58','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (65,6146,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-16 22:31:58','2020-08-16 22:31:58','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (66,6146,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-16 22:31:58','2020-08-16 22:31:58','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (67,6147,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-18 01:04:38','2020-08-18 01:04:38','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (68,6147,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-18 01:04:38','2020-08-18 01:04:38','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (69,6148,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-18 05:42:06','2020-08-18 05:42:06','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (70,6149,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-18 16:25:53','2020-08-18 16:25:53','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (71,6150,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-18 17:30:41','2020-08-18 17:30:41','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (72,6150,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-18 17:30:42','2020-08-18 17:30:42','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (73,6151,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-18 17:45:44','2020-08-18 17:45:44','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (74,6151,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-18 17:45:44','2020-08-18 17:45:44','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (75,6147,'Gerardo Corvalan','infoarcapet@gmail.com','','','2020-08-18 18:43:49','2020-08-18 18:43:49','El estado del pedido cambió de Procesando a Completado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (76,6152,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-18 20:26:55','2020-08-18 20:26:55','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (77,6153,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-19 06:14:53','2020-08-19 06:14:53','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (78,6154,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-19 16:12:14','2020-08-19 16:12:14','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (79,6146,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-19 16:23:55','2020-08-19 16:23:55','El estado del pedido cambió de Procesando a Reembolsado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (80,6156,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-19 19:19:53','2020-08-19 19:19:53','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (81,6158,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-20 01:35:38','2020-08-20 01:35:38','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (82,6158,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-20 01:35:39','2020-08-20 01:35:39','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (83,6157,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-20 01:35:45','2020-08-20 01:35:45','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (84,6157,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-20 01:35:45','2020-08-20 01:35:45','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (85,6239,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-23 17:48:47','2020-08-23 17:48:47','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (86,6239,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-23 17:48:47','2020-08-23 17:48:47','Niveles de inventario reducidos: Collar Zee.Cat Ella (#3180) 10&rarr;9',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (87,6239,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-23 17:48:47','2020-08-23 17:48:47','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (88,6253,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-23 22:56:31','2020-08-23 22:56:31','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (89,6253,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-23 22:56:31','2020-08-23 22:56:31','Niveles de inventario reducidos: Alfombra Guarda Premios (#4508) 10&rarr;9',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (90,6253,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-23 22:56:31','2020-08-23 22:56:31','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (91,6272,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-24 05:39:28','2020-08-24 05:39:28','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (92,6272,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-24 05:39:29','2020-08-24 05:39:29','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (93,6273,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-24 08:23:34','2020-08-24 08:23:34','El pedido sin pagar ha sido cancelado - se ha alcanzado el limite de tiempo. El estado del pedido cambió de Pendiente de pago a Cancelado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (94,6157,'Gerardo Corvalan','infoarcapet@gmail.com','','','2020-08-24 18:38:26','2020-08-24 18:38:26','El estado del pedido cambió de Procesando a Completado.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (95,6276,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-24 21:05:56','2020-08-24 21:05:56','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (96,6276,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-24 21:05:56','2020-08-24 21:05:56','Niveles de inventario reducidos: Animal Mutante \"Porkdufant\" Zee.Dog (11900) 3&rarr;2',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (97,6276,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-24 21:05:56','2020-08-24 21:05:56','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (98,6291,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-27 20:22:44','2020-08-27 20:22:44','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (99,6291,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-27 20:22:44','2020-08-27 20:22:44','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (100,6292,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-27 23:41:36','2020-08-27 23:41:36','Pagado con flow',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (101,6292,'WooCommerce','woocommerce@arcapet.cl','','','2020-08-27 23:41:36','2020-08-27 23:41:36','El estado del pedido cambió de Pendiente de pago a Procesando.',0,'1','WooCommerce','order_note',0,0);
