/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `wp_users` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_login` varchar(60) NOT NULL DEFAULT '',
  `user_pass` varchar(255) NOT NULL DEFAULT '',
  `user_nicename` varchar(50) NOT NULL DEFAULT '',
  `user_email` varchar(100) NOT NULL DEFAULT '',
  `user_url` varchar(100) NOT NULL DEFAULT '',
  `user_registered` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `user_activation_key` varchar(255) NOT NULL DEFAULT '',
  `user_status` int(11) NOT NULL DEFAULT 0,
  `display_name` varchar(250) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `user_login_key` (`user_login`),
  KEY `user_nicename` (`user_nicename`),
  KEY `user_email` (`user_email`)
) ENGINE=InnoDB AUTO_INCREMENT=181778644 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778603,'ArcaPET','$P$BPxSZfY9qMzph5Zyu5TGTfjteKfCbQ1','arcapet','infoarcapet@gmail.com','','2020-05-29 23:23:20','',0,'Gerardo Corvalan');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778604,'laura.marambio','$P$BJgPbjWUMmmbgvTvN/1IrBcyW3p3.S/','laura-marambio','laura.marambio.gomez@gmail.com','','2020-06-30 21:02:51','',0,'Laura Marambio');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778605,'jaime.valle silva','$P$B3CeU0A3wtcZXbnRsG9OyATj1GQePP1','jaime-valle-silva','jvalle@ug.uchile.cl','','2020-07-01 02:20:06','',0,'Jaime Valle Silva');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778606,'stephanie.barahona','$P$BK325AJam.37RRln8PixmWIfUfpLnv/','stephanie-barahona','stephanie_barahona@live.cl','','2020-07-04 19:21:19','',0,'Stephanie Barahona');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778607,'bastian.ortiz','$P$B52H5TAYADft5LTktzgw8ox5LxNOCu.','bastian-ortiz','bortiz994@gmail.com','','2020-07-06 01:25:52','',0,'Bastian Ortiz');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778608,'valentina.alvarez','$P$BB4DhtP4wSawCiLNgCo.FUV.5peGgt.','valentina-alvarez','vale.mujica@hotmail.com','','2020-07-11 14:13:14','',0,'Valentina Álvarez');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778609,'lizzi.gonzalez alvarez','$P$BVUKZ3MHlnntba5I9i.1x8sq39EloU0','lizzi-gonzalez-alvarez','Lizzygonzalez0112@outlook.com','','2020-07-12 01:57:25','',0,'Lizzi González Álvarez');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778610,'prueba.para arcapet','$P$Bmx1XeniCz3OjhaNIwXhP22jiK2.yd/','prueba-para-arcapet','jorge.alvarez.quiero@gmail.com','','2020-07-12 02:07:30','',0,'Prueba Para ArcaPet');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778611,'natalia.monasterio moraga','$P$BscBu0NSqQtNDBzVCpsGNomYNRwWjl/','natalia-monasterio-moraga','natalia.monasterio.m@gmail.com','','2020-07-14 15:04:32','',0,'Natalia Monasterio Moraga');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778612,'ivonne.chavarria','$P$BzD6Ui5oeC/U8u7sic717OD121W7HB.','ivonne-chavarria','ivonnechavarriaa@gmail.com','','2020-07-16 17:31:56','',0,'Ivonne Chavarria');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778613,'karl.gomez','$P$B/ZZ7OJASE7sB3Oi.xem28b9cHDCa1.','karl-gomez','karlgmezc@gmail.com','','2020-07-17 18:08:20','',0,'karl gomez');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778614,'andrea.canales','$P$BJqgya/TC6qTY2RPYwSbKiOyh9YzFM0','andrea-canales','acanalesr@udd.cl','','2020-07-21 19:28:37','',0,'ANDREA CANALES');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778615,'viviana.pezo symmer','$P$BGioI8Pl1leVG.QlCc4QgYBotN3b.91','viviana-pezo-symmer','viviana.pezo@gmail.com','','2020-07-26 16:52:53','',0,'Viviana Pezo symmer');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778616,'karin.munoz silva','$P$BdiPgbKlkHcjauTL3NII/TYUdI.MwL0','karin-munoz-silva','karin.munoz.silva@gmail.com','','2020-07-30 16:34:26','',0,'karin muñoz silva');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778617,'camila.vasquez','$P$BjOr/ifJDGryzXhvtenYVbBEl8OheS1','camila-vasquez','camilavasquez005@gmail.com','','2020-08-05 14:17:01','',0,'Camila Vásquez');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778618,'alejandra.troncoso espinosa','$P$BV5u.H15Ys6w0DxXpQBgx9GCE0nFJv0','alejandra-troncoso-espinosa','alejandra_jv@hotmail.com','','2020-08-11 22:14:57','',0,'Alejandra Troncoso Espinosa');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778619,'michael.avila','$P$BI4BSSNicPNmvVGpBdChm7fLg7OLNo/','michael-avila','maavila9502@gmail.com','','2020-08-12 17:33:19','',0,'Michael Avila');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778620,'maria.santis ureta','$P$Bb6.nXp1lroICILBt3NKKbt2VgeJSw/','maria-santis-ureta','u-reta@live.com','','2020-08-14 02:32:59','',0,'Maria Santis Ureta');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778621,'pilar.pavez soto','$P$BqqryS5RKwmzqcgjkhpL40lrHQa/JB0','pilar-pavez-soto','pilarpavezsoto@gmail.com','','2020-08-14 03:10:56','',0,'Pilar Pavez soto');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778622,'andrea.canales-8829','$P$BoZU5k5Zx7R2BX0f7WWKMOKKOAfLjw.','andrea-canales-8829','acanalesr1997@gmail.com','','2020-08-14 03:56:56','',0,'ANDREA CANALES');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778623,'mariapaz.rivera lobos','$P$BcqVd3OJHDpyiPPLYkDCZdeNK8dd.e.','mariapaz-rivera-lobos','mariapaz397@hotmail.com','','2020-08-14 19:14:23','',0,'Mariapaz Rivera Lobos');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778624,'valentina.gutierrez garay','$P$Bcl3BTEdwdUnk0Ot8A08Mh.h9W1WmF.','valentina-gutierrez-garay','vgg9788@gmail.com','','2020-08-14 21:29:54','',0,'Valentina Gutiérrez Garay');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778625,'trinidad.arancibia','$P$BKgCmzErZpzNr5mKQUvDqYNeHrL5pV0','trinidad-arancibia','triniarancibia@yahoo.es','','2020-08-15 04:45:13','',0,'Trinidad Arancibia');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778626,'maria eugenia.meneses farias','$P$Bk3Na5EQ2elUm6iL1Y4mqptzKONMkx1','maria-eugenia-meneses-farias','mary.menesesfarias@gmail.com','','2020-08-15 14:59:59','',0,'María Eugenia Meneses Farias');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778627,'erika.porter marin','$P$BXFoL7c8t6kkXzeEJUQ5mDI/Ts/8Sg/','erika-porter-marin','erika.porter18@gmail.com','','2020-08-15 15:31:21','',0,'Erika Porter Marin');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778628,'nelson.barrera','$P$BIz76zpbaumO6le/4N6xanYtY.V4P..','nelson-barrera','nelson.barval@gmail.com','','2020-08-16 22:29:58','',0,'NELSON BARRERA');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778629,'natalia.barrientos','$P$B2p0NR5ezO0ALjwZ9KyxMa7jfc7/Yo.','natalia-barrientos','nataliafbp@gmail.com','','2020-08-18 01:00:01','',0,'Natalia Barrientos');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778630,'carolina.abarca','$P$BLbCoxWf8dmFtOcWnuZANHkD6.KWWR1','carolina-abarca','carolinaabarcaegana@gmail.com','','2020-08-18 04:35:18','',0,'Carolina Abarca');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778631,'sofia.nunez pinto','$P$BBaS6XhaDYSf2S47Bise/a4PFC7Qbd0','sofia-nunez-pinto','sofiaignacia1611@gmail.com','','2020-08-18 14:49:21','',0,'Sofía Núñez Pinto');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778632,'cinthia.marin gomez','$P$BYXK/BraREpoYmsHW4HKbwU.0ayp.21','cinthia-marin-gomez','ccmaringomez@gmail.com','','2020-08-18 17:26:21','',0,'Cinthia Marin Gomez');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778633,'denisse.biscarra valenzuela','$P$BAyWPxdP48iRiTHp7QlXXXRuEbrU8n/','denisse-biscarra-valenzuela','denisse.biscarra4@gmail.com','','2020-08-18 17:43:37','',0,'Denisse Biscarra Valenzuela');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778634,'franshesca.munoz ibarra','$P$BKIu6LF0u0MK4AbEcdozc0calzZKrT1','franshesca-munoz-ibarra','franshesca_@live.cl','','2020-08-18 19:18:24','',0,'Franshesca Muñoz Ibarra');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778635,'elimarys.tineo','$P$B.Tb3ooGZct3i2z8vEIfvEi7IDBqP10','elimarys-tineo','elimarystm@gmail.com','','2020-08-19 14:50:32','',0,'Elimarys Tineo');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778636,'jazmin.cabrera yanez','$P$BstJ3bCa8r6ZhqVw3tXqQp8.BYRc4V/','jazmin-cabrera-yanez','jcabrerayz@gmail.com','','2020-08-20 01:33:35','',0,'Jazmín Cabrera Yáñez');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778637,'alfredo.niklitschek dabike','$P$BQbddXoJfUQM23tOxAq0skgj/UkXYy.','alfredo-niklitschek-dabike','aanikli@gmail.com','','2020-08-20 01:33:52','',0,'Alfredo Niklitschek Dabiké');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778638,'paola.melin','$P$BzwkSYtEMFK9YMNp.ncBjGCBhOZ1yU.','paola-melin','paolamelin@gmail.com','','2020-08-23 17:46:37','',0,'Paola Melin');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778639,'francisca.ferrada','$P$BY/sq7bRWfLEVWWmqPw4vzeEeqMiP71','francisca-ferrada','FRAN.FERRADAMEJIAS@GMAIL.COM','','2020-08-23 22:54:22','',0,'Francisca Ferrada');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778640,'marcelo.cabrera nilo','$P$BlGXLSyFbxa112RnO5sVLP3NXuy7N..','marcelo-cabrera-nilo','marcelo.cabreran@gmail.com','','2020-08-24 05:37:24','',0,'Marcelo Cabrera Nilo');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778641,'josetomas.raposo','$P$BNFEQJCqeEAbuDPqXLBP/NXlHWIeOh/','josetomas-raposo','joseraposo.ps@gmail.com','','2020-08-24 06:48:59','',0,'josetomas raposo');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778642,'daniela.cardemil','$P$B3ZRLtip7DCLoZG4XixwFCV4/4FpFn0','daniela-cardemil','dcardemilsantos@gmail.com','','2020-08-24 21:03:32','',0,'Daniela Cardemil');
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES (181778643,'sofia.barrientos','$P$BOpKvCj117G2ay7BBoFWeqA5dwmcmW0','sofia-barrientos','sofia.barrientosp@gmail.com','','2020-08-27 20:20:53','',0,'Sofía Barrientos');
