/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `wp_woocommerce_order_items` (
  `order_item_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_item_name` text NOT NULL,
  `order_item_type` varchar(200) NOT NULL DEFAULT '',
  `order_id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`order_item_id`),
  KEY `order_id` (`order_id`)
) ENGINE=InnoDB AUTO_INCREMENT=172 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (4,'Hueso para perritos','line_item',1255);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (5,'Hueso para perritos','line_item',1256);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (6,'Hueso para perritos','line_item',1258);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (7,'Hueso para perritos','line_item',1259);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (10,'Hueso para perritos','line_item',1262);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (11,'Hueso para perritos','line_item',1261);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (12,'Hueso para perritos','line_item',1263);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (13,'Hueso para perritos','line_item',1264);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (14,'Royal Canin Yorkshire Terrier Adulto 2.5Kg','line_item',4229);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (15,'Snack Mr. Woof Para Perro Carne Zanahoria 30 Unidades','line_item',4233);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (16,'Royal Canin Mini Junior 1Kg','line_item',4751);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (17,'Royal Canin Pug Junior','line_item',4753);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (18,'Dental Care Trixie','line_item',5155);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (19,'Corta Uñas Talla L','line_item',5155);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (20,'Set Cepillos de dientes','line_item',5155);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (21,'Dental Care Trixie','line_item',5157);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (22,'Corta Uñas Talla L','line_item',5157);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (23,'Set Cepillos de dientes','line_item',5157);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (24,'Guantes Saca Pelos','line_item',5157);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (26,'Air Mesh Plus Zee.Dog Same - S','line_item',5257);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (27,'Guantes Saca Pelos','line_item',5255);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (28,'PET’S DREAM - Sustrato ecológico de papel','line_item',5439);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (29,'Royal Canin Kitten 2da Etapa - 1,5','line_item',5584);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (30,'The Cat\'s Tail Premios','line_item',5613);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (31,'Maipu','shipping',5613);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (32,'Canish Espuma Shampoo en seco','line_item',5767);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (33,'Furminator Long Hair','line_item',5767);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (34,'Santiago Centro','shipping',5767);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (35,'Canish Espuma Shampoo en seco','line_item',5768);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (36,'Furminator Long Hair','line_item',5768);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (37,'Providencia','shipping',5768);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (38,'Canish Espuma Shampoo en seco','line_item',5769);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (39,'Furminator Long Hair','line_item',5769);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (40,'Recogida local','shipping',5769);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (41,'Snack Mr. Woof Para Perro Carne Zanahoria 30 Unidades','line_item',5924);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (42,'Snack Mr. Woof Para Perro Pollo Zanahoria 30 Unidades','line_item',5924);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (43,'Ñuñoa','shipping',5924);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (44,'Arnés Zee.Cat Atlanta','line_item',5967);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (45,'Cinturón de Seguridad para Autos','line_item',5967);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (46,'Doguitos (Tiras de asado)','line_item',5967);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (47,'Conchalì','shipping',5967);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (54,'Cama Gris Suave con chiporro - L','line_item',5968);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (55,'Plato anti-estrés','line_item',5968);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (56,'Baño Para Perro Mediano','line_item',5968);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (57,'Collar Zee.Dog NEOPRO Tangerine - M','line_item',5968);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (58,'Pelota de Tenis con Cuerda','line_item',5968);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (59,'Recogida local','shipping',5968);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (64,'Gramera Digital de Comida','line_item',6021);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (65,'Lo Prado','shipping',6021);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (66,'Cepillo Eliminador de Pelos','line_item',6023);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (67,'Cepillo Furminator Short Hair','line_item',6023);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (68,'Sabanillas 30 und .Chao Pipi . 60x60cm','line_item',6023);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (69,'Snack Mr. Woof Para Perro Pollo Zanahoria 30 Unidades','line_item',6023);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (70,'Bolsas para Desechos 3 Rollos','line_item',6023);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (71,'Corta Uñas talla M','line_item',6023);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (72,'Ñuñoa','shipping',6023);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (79,'INVERMIC ® GATO - Solución Oral','line_item',6028);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (80,'Fiprodrag gatos mayores a 12 semanas','line_item',6028);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (81,'Recogida local','shipping',6028);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (82,'Mochila Panorámica Rosa','line_item',6032);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (83,'Envío gratuito','shipping',6032);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (84,'Cama Redonda Lila Claro','line_item',6095);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (85,'Santiago Centro','shipping',6095);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (86,'Cama Redonda Lila Claro','line_item',6109);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (87,'Recogida local','shipping',6109);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (88,'Air Mesh Plus Zee.Dog Same - L','line_item',6110);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (89,'Correa Zee.Dog Same - S','line_item',6110);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (90,'Collar Zee.Dog Same - L','line_item',6110);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (91,'Conchalì','shipping',6110);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (92,'Cama Redonda Lila Claro','line_item',6111);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (93,'Recogida local','shipping',6111);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (94,'Cama Redonda Peludita - XL','line_item',6124);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (95,'Huechuraba','shipping',6124);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (96,'Cama Redonda Peludita - M','line_item',6129);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (97,'San Miguel','shipping',6129);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (98,'Cama Redonda Peludita - M','line_item',6137);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (99,'Las Condes','shipping',6137);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (100,'Juguete de Perro Herradura','line_item',6138);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (101,'Warrior Pelota para Limpieza Dental','line_item',6138);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (102,'Recogida local','shipping',6138);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (103,'Cama Redonda Peludita - XL','line_item',6139);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (104,'Ñuñoa','shipping',6139);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (105,'Cama Gris Suave con chiporro - L','line_item',6146);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (106,'Envío gratuito','shipping',6146);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (110,'Cama Redonda Peludita - M','line_item',6147);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (111,'Cama Redonda Peludita - XL','line_item',6147);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (112,'Envío gratuito','shipping',6147);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (113,'Cama Redonda Peludita - XL','line_item',6148);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (114,'Recogida local','shipping',6148);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (115,'Cama Redonda Peludita - M','line_item',6149);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (116,'Recogida local','shipping',6149);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (117,'Collar Zee.Cat Phantom','line_item',6150);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (118,'Hierba Gatera','line_item',6150);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (119,'Santiago Centro','shipping',6150);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (120,'Cama Redonda Peludita - XL','line_item',6151);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (121,'Royal Canin Young Male 1.5Kg','line_item',6151);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (122,'Churu Sabor Atún','line_item',6151);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (123,'Recogida local','shipping',6151);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (124,'Cama Redonda Peludita - XL','line_item',6152);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (125,'Recogida local','shipping',6152);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (126,'Cama Redonda Peludita - L','line_item',6153);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (127,'Recogida local','shipping',6153);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (128,'Apetipet','line_item',6154);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (129,'Placa Calefactora Para Erizo 20 w.','line_item',6154);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (130,'Santiago Centro','shipping',6154);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (131,'Cama Gris Suave con chiporro - L','line_item',6155);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (135,'Apetipet','line_item',6156);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (136,'Placa Calefactora Para Erizo 20 w.','line_item',6156);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (137,'Recogida local','shipping',6156);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (138,'Cama Gris Suave con chiporro - M','line_item',6157);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (139,'Quilicura','shipping',6157);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (140,'Collar Zee.Dog Crosby - XS','line_item',6158);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (141,'Correa Zee.Dog Crosby - XS','line_item',6158);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (142,'Las Condes','shipping',6158);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (143,'Cama de Gato para Ventana','line_item',6239);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (144,'Collar Zee.Cat Ella','line_item',6239);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (145,'Recogida local','shipping',6239);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (146,'Juguete de Gato con Movimiento','line_item',6253);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (147,'Alfombra Guarda Premios','line_item',6253);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (148,'San Joaquin','shipping',6253);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (149,'Gramera Digital de Comida','line_item',6272);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (150,'Maipu','shipping',6272);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (151,'Correa Zee.Dog Ruff Leash Tide Gradientes','line_item',6273);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (152,'Air Mesh Plus Zee.Dog Tide - L','line_item',6273);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (153,'Envío gratuito','shipping',6273);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (154,'Cama de Gato para Ventana','line_item',6276);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (155,'Juguete de Gato con Movimiento','line_item',6276);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (156,'Animal Mutante \"Porkdufant\" Zee.Dog','line_item',6276);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (157,'Envío gratuito','shipping',6276);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (158,'Bolso de Transporte Rojo y Negro','line_item',6288);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (159,'Atrapa el Ratón!','line_item',6288);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (160,'La Florida','shipping',6288);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (161,'Bolso de Transporte Rojo y Negro','line_item',6289);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (162,'Atrapa el Ratón!','line_item',6289);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (163,'La Florida','shipping',6290);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (164,'Cama Redonda Peludita - XL','line_item',6291);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (165,'Cama Redonda Peludita - XL','line_item',6291);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (166,'Cama Redonda Peludita - L','line_item',6291);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (167,'Envío gratuito','shipping',6291);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (168,'Snack Mr. Woof Para Perro Carne Zanahoria 30 Unidades','line_item',6292);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (169,'Snack Mr. Woof Para Perros Dulce Tropical 30 Unidades','line_item',6292);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (170,'Snack Mr. Woof Para Perro Pollo Zanahoria 30 Unidades','line_item',6292);
INSERT INTO `wp_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (171,'Ñuñoa','shipping',6292);
REPLACE INTO `wp_woocommerce_order_items` (`order_item_id`,`order_item_name`,`order_item_type`,`order_id`) VALUES ('164','Cama Redonda Peludita - XL','line_item','6291');
REPLACE INTO `wp_woocommerce_order_items` (`order_item_id`,`order_item_name`,`order_item_type`,`order_id`) VALUES ('165','Cama Redonda Peludita - XL','line_item','6291');
REPLACE INTO `wp_woocommerce_order_items` (`order_item_id`,`order_item_name`,`order_item_type`,`order_id`) VALUES ('166','Cama Redonda Peludita - L','line_item','6291');
REPLACE INTO `wp_woocommerce_order_items` (`order_item_id`,`order_item_name`,`order_item_type`,`order_id`) VALUES ('167','Envío gratuito','shipping','6291');
REPLACE INTO `wp_woocommerce_order_items` (`order_item_id`,`order_item_name`,`order_item_type`,`order_id`) VALUES ('168','Snack Mr. Woof Para Perro Carne Zanahoria 30 Unidades','line_item','6292');
REPLACE INTO `wp_woocommerce_order_items` (`order_item_id`,`order_item_name`,`order_item_type`,`order_id`) VALUES ('169','Snack Mr. Woof Para Perros Dulce Tropical 30 Unidades','line_item','6292');
REPLACE INTO `wp_woocommerce_order_items` (`order_item_id`,`order_item_name`,`order_item_type`,`order_id`) VALUES ('170','Snack Mr. Woof Para Perro Pollo Zanahoria 30 Unidades','line_item','6292');
REPLACE INTO `wp_woocommerce_order_items` (`order_item_id`,`order_item_name`,`order_item_type`,`order_id`) VALUES ('171','Ñuñoa','shipping','6292');
