/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `wp_wc_admin_notes` (
  `note_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `type` varchar(20) NOT NULL,
  `locale` varchar(20) NOT NULL,
  `title` longtext NOT NULL,
  `content` longtext NOT NULL,
  `icon` varchar(200) NOT NULL DEFAULT 'info',
  `content_data` longtext DEFAULT NULL,
  `status` varchar(200) NOT NULL,
  `source` varchar(200) NOT NULL,
  `date_created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `date_reminder` datetime DEFAULT NULL,
  `is_snoozable` tinyint(1) NOT NULL DEFAULT 0,
  `layout` varchar(20) NOT NULL DEFAULT '',
  `image` varchar(200) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`note_id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (3,'wc-admin-wc-helper-connection','info','en_US','Connect to WooCommerce.com','Connect to get important product notifications and updates.','info','{}','unactioned','woocommerce-admin','2020-05-08 07:17:39',NULL,0,'',NULL,0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (4,'wc-admin-onboarding-profiler-reminder','update','en_US','Welcome to WooCommerce! Set up your store and start selling','We\'re here to help you going through the most important steps to get your store up and running.','info','{}','actioned','woocommerce-admin','2020-05-08 07:22:32',NULL,0,'plain',NULL,0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (5,'wc-admin-mobile-app','info','en_US','Instala la aplicación móvil WooCommerce','Instala la aplicación móvil de WooCommerce para gestionar pedidos, recibir avisos de ventas y ver métricas clave – allí donde estés.','phone','{}','unactioned','woocommerce-admin','2020-05-10 11:08:39',NULL,0,'',NULL,0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (6,'wc-admin-onboarding-email-marketing','info','en_US','Trucos, actualizaciones de productos e inspiración','Estamos aquí por ti - consigue trucos, actualizaciones de productos e inspiración en tu buzón.','mail','{}','unactioned','woocommerce-admin','2020-05-10 11:08:39',NULL,0,'',NULL,0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (8,'wc-admin-facebook-extension','info','en_US','Vende en Facebook','Haz crecer tu negocio dirigiéndote a las personas adecuadas e impulsando las ventas con Facebook. Puedes instalar ahora esta extensión gratuita.','thumbs-up','{}','unactioned','woocommerce-admin','2020-05-24 07:42:42',NULL,0,'',NULL,0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (10,'wc-admin-marketing-intro','info','en_US','Connect with your audience','Grow your customer base and increase your sales with marketing tools built for WooCommerce.','speaker','{}','unactioned','woocommerce-admin','2020-06-03 09:23:42',NULL,0,'',NULL,0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (12,'wc-admin-store-notice-giving-feedback-2','info','en_US','Give feedback','Now that you’ve chosen us as a partner, our goal is to make sure we\'re providing the right tools to meet your needs. We\'re looking forward to having your feedback on the store setup experience so we can improve it in the future.','info','{}','unactioned','woocommerce-admin','2020-07-09 07:17:46',NULL,0,'plain','',0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (13,'wc-admin-real-time-order-alerts','info','en_US','Get real-time order alerts anywhere','Get notifications about store activity, including new orders and product reviews directly on your mobile devices with the Woo app.','info','{}','unactioned','woocommerce-admin','2020-07-09 07:17:46',NULL,0,'plain','',0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (18,'wc-admin-orders-milestone','info','en_US','¡Enhorabuena por haber procesado 10 pedidos!','¡Has logrado el hito de los 10 pedidos! Mira cómo vas. Ve algunas historias de éxito de WooCommerce para inspirarte.','info','{}','unactioned','woocommerce-admin','2020-08-09 15:20:07',NULL,0,'plain','',0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (19,'wc-admin-new-sales-record','info','en_US','¡Nuevo récord de ventas!','¡Ole, August 14th fue tu día récord de ventas! La facturación neta fue de $144.500 superando el récord anterior de $104.400 establecido el July 30th.','info','{\"old_record_date\":\"2020-07-30\",\"old_record_amt\":104400,\"new_record_date\":\"2020-08-14\",\"new_record_amt\":144500}','unactioned','woocommerce-admin','2020-08-15 07:23:05',NULL,0,'plain','',0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (20,'ecomm-need-help-setting-up-your-store','info','en_US','Need help setting up your Store?','Schedule a free 30-min <a href=\"https://wordpress.com/support/concierge-support/\">quick start session</a> and get help from our specialists. We’re happy to walk through setup steps, show you around the WordPress.com dashboard, troubleshoot any issues you may have, and help you the find the features you need to accomplish your goals for your site.','info','{}','pending','woocommerce.com','2020-08-22 05:50:37',NULL,0,'plain','',0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (21,'woocommerce-services','info','en_US','WooCommerce Services','WooCommerce Services helps get your store “ready to sell” as quickly as possible. You create your products. We take care of tax calculation, payment processing, and shipping label printing! Learn more about the extension that you just installed.','info','{}','pending','woocommerce.com','2020-08-22 05:50:37',NULL,0,'plain','',0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (22,'ecomm-unique-shopping-experience','info','en_US','For a shopping experience as unique as your customers','Product Add-Ons allow your customers to personalize products while they’re shopping on your online store. No more follow-up email requests—customers get what they want, before they’re done checking out. Learn more about this extension that comes included in your plan.','info','{}','pending','woocommerce.com','2020-08-22 05:50:37',NULL,0,'plain','',0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (23,'wc-admin-insight-first-sale','survey','en_US','Did you know?','A WooCommerce powered store needs on average 31 days to get the first sale. You\'re on the right track! Do you find this type of insight useful?','info','{}','unactioned','woocommerce-admin','2020-08-22 07:21:17',NULL,0,'plain','',0);
INSERT INTO `wp_wc_admin_notes` (`note_id`, `name`, `type`, `locale`, `title`, `content`, `icon`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`) VALUES (24,'wc-admin-home-screen-feedback','info','en_US','Ayúdanos a mejorar la pantalla de inicio de WooCommerce','Nos encantaría saber tu opinión para dar forma al futuro de la pantalla de inicio de WooCommerce juntos. No dudes en compartir cualquier comentario, idea o sugerencia que tengas.','info','{}','unactioned','woocommerce-admin','2020-08-27 19:25:50',NULL,0,'plain','',0);
