/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `wp_yoast_seo_links` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `url` varchar(255) NOT NULL,
  `post_id` bigint(20) unsigned NOT NULL,
  `target_post_id` bigint(20) unsigned NOT NULL,
  `type` varchar(8) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `link_direction` (`post_id`,`type`)
) ENGINE=InnoDB AUTO_INCREMENT=2603 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (9,'#',20,0,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (10,'#',20,0,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (603,'https://arcapet.cl/',16,15,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (604,'https://arcapet.cl/',16,15,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (605,'https://arcapet.cl/',16,15,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (606,'https://arcapet.cl/',16,15,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (816,'https://vimeo.com/22439234',1487,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (817,'https://github.com/WordPress/gutenberg',1487,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (818,'https://github.com/WordPress/gutenberg',1487,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (836,'https://arcapet.cl/',576,15,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2242,'https://arcapet.cl',3,15,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2243,'https://www.paypal.com/es/webapps/mpp/ua/privacy-full',3,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2401,'#',91,0,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2402,'https://www.facebook.com/arcapet.cl',91,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2403,'https://www.instagram.com/arcapet.cl',91,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2414,'https://www.amigales.cl/marcas/zee-dog.html',3331,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2416,'https://www.amigales.cl/marcas/zee-dog.html',3156,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2419,'https://www.amigales.cl/marcas/zee-dog.html',2849,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2421,'https://www.amigales.cl/marcas/zee-dog.html',2834,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2422,'https://www.amigales.cl/marcas/zee-dog.html',2818,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2425,'https://www.amigales.cl/marcas/zee-dog.html',2411,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2428,'https://www.amigales.cl/marcas/zee-dog.html',2398,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2431,'https://www.amigales.cl/marcas/zee-dog.html',2288,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2434,'https://www.amigales.cl/marcas/zee-dog.html',2103,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2435,'https://www.amigales.cl/marcas/zee-dog.html',2020,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2436,'https://www.amigales.cl/marcas/zee-dog.html',1993,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2437,'https://www.amigales.cl/marcas/zee-dog.html',1824,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2438,'https://www.amigales.cl/marcas/zee-dog.html',1806,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2439,'https://www.amigales.cl/marcas/zee-dog.html',2840,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2440,'https://www.amigales.cl/marcas/zee-dog.html',3867,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2442,'https://www.amigales.cl/marcas/zee-dog.html',3814,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2443,'https://www.amigales.cl/marcas/zee-dog.html',2112,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2445,'https://www.amigales.cl/marcas/zee-dog.html',2851,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2446,'https://www.amigales.cl/marcas/zee-dog.html',2084,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2448,'https://www.amigales.cl/marcas/zee-dog.html',5327,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2449,'https://www.amigales.cl/marcas/zee-dog.html',3464,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2450,'https://www.amigales.cl/marcas/zee-dog.html',2356,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2451,'https://www.amigales.cl/marcas/zee-dog.html',2365,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2452,'https://www.amigales.cl/marcas/zee-dog.html',2540,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2453,'https://www.amigales.cl/marcas/zee-dog.html',3624,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2454,'https://www.amigales.cl/marcas/zee-dog.html',3611,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2455,'https://www.amigales.cl/marcas/zee-dog.html',2558,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2457,'https://www.amigales.cl/pelota-futbol-mango-jumball.html',5862,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2556,'https://arcapet.cl/tienda-online/',15,0,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2557,'https://arcapet.cl/categoria-producto/tys/',15,0,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2558,'https://arcapet.cl/categoria-producto/syb/',15,0,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2559,'https://arcapet.cl/categoria-producto/vya/',15,0,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2560,'https://arcapet.cl/categoria-producto/cye/',15,0,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2561,'https://arcapet.cl/categoria-producto/snacks/',15,0,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2562,'https://arcapet.cl/categoria-producto/pub/',15,0,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2563,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2564,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2565,'https://arcapet.cl/tienda-online/',15,0,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2566,'https://arcapet.cl/tienda-online/',15,0,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2567,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2568,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2569,'https://arcapet.cl/quienes-somos/',15,16,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2570,'https://www.facebook.com/Arcapetcl/',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2571,'https://www.instagram.com/arcapet.cl/',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2572,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2573,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2574,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2575,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2576,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2577,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2578,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2579,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2580,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2581,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2582,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2583,'https://arcapet.cl/servicios/',15,18,'internal');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2584,'https://i0.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-1.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2585,'https://i1.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-2.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2586,'https://i0.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-3.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2587,'https://i1.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-4.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2588,'https://i2.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-5.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2589,'https://i1.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-6.jpg?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2590,'https://i2.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-7.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2591,'https://i1.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-8.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2592,'https://i2.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-9.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2593,'https://i0.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-10.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2594,'https://i2.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-11.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2595,'https://i1.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-12.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2596,'https://i0.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-13.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2597,'https://i1.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-14.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2598,'https://i0.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-15.jpg?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2599,'https://i2.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-16.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2600,'https://i0.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-17.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2601,'https://i2.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-18.png?ssl=1',15,0,'external');
INSERT INTO `wp_yoast_seo_links` (`id`, `url`, `post_id`, `target_post_id`, `type`) VALUES (2602,'https://i1.wp.com/arcapet.cl/wp-content/uploads/2020/06/logo-19.png?ssl=1',15,0,'external');
